config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index , :show] do
    resources :comments,only:[:create, :destroy]
    #瀏覽所有餐廳的最進動態
    collection do
      get :feeds
    end
    #瀏覽個別餐廳的Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end

    member do
      get :dashboard
      post :like
      post :unlike
    end
  end
  resources :users,only: [:index ,:show , :edit, :update]

  resources :categories, only: :show
  resources :followships, only: [:create, :destroy]
  root "restaurants#index"

  namespace :admin do
    resources :restaurants 
    resources :categories
    root "restaurants#index"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :restaurants , dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }
  
  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, PhotoUploader
  belongs_to :category
  has_many :comments , dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships
  
  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin

  private

    def authenticate_admin
      unless current_user.admin?
        flash[:alert] = "Not allow?"
        redirect_to root_path
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # private

  # def authenticate_admin
  #   unless current_user.admin?
  #     flash[:alert] = "Not allow!"
  #     redirect_to root_path
  #   end
  # end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant =Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end
  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  def create
    @followship = current_user.followships.build(following_id: params[:following_id])

    if @followship.save
      flash[:notice] = "Successfully followed"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    # where 會回傳物件集合(Array)，需要串接可取出單一物件的方法如 first
    @followship = current_user.followships.where(following_id: params[:id]).first
    @followship.destroy
    flash[:alert] = "Followship destroyed"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :authenticate_user!
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all     # 加上這一行
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

    # POST /restaurants/:id/favorite
  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

 def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :set_user, only: [:show, :edit, :update]
  
  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
  end
  def edit
    
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "user was successfully updated"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "user was failed to update"
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)  
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/reataurants_helper.rb
module Admin::ReataurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    
    <h3><strong>Edit Profile</strong></h3>

    <%= form_for @user do |f| %>
           <div class="form-group">
             <%= f.label :name, "Name" %>
             <%= f.text_field :name, class: "form-control" %>
           </div>

           <div class="form-group">
             <%= f.label :intro, "自我介紹" %>
             <%= f.text_field :intro, class: "form-control" %>
           </div>

           <div class="form-group">
             <%= f.label :avatar, "大頭照上傳" %>
             <%= image_tag @user.avatar, width: '300px' if @user.avatar? %>
             <%= f.file_field :avatar %>
           </div> 
           <div class="form-group">
             <%= f.submit "Update", class: "btn btn-primary" %>
             <%= link_to "Cancel",user_path(@user),class: "btn btn-default" %>
           </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div> 
    <ul class="nav nav-tabs">
      <li role="presentation" >
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path  %>
      </li>
      <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="row">

    <div class="col-md-12">
      <div class="page-header">
        <h1>美食達人</h1>
      </div>
    </div>

    <% @users.each do |user| %>
      <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">

        <%= link_to user_path(user) do %>
          <!-- 可先利用 Placeholder 如 <img src="http://via.placeholder.com/128x128"> 產生圖片 -->
          <%= image_tag(user.avatar, class: "img-rounded") %>
          <h4><%= user.name %></h4>
        <% end %>

        <%= render partial: "shared/follow", locals: {user: user} %>

      </div>
    <% end %>
</div>
 

app/views/users/show.html.erb
 <div class="container">
  <div class="row">
   <div class="col-md-10 col-md-offset-1">
       <div class="page-header">

      <div class="col-md-3 col-sm-4">
        <div class="text-center">
         <%= image_tag @user.avatar, width: '300px',class: "img-responsive center-block" %>
        </div>
       </div>
        
      
      <div class="col-md-9 col-sm-8">
        <div><strong><h1><%= @user.name %></h1></strong></div>
        <div><%= @user.email %></div>
        <div><%= simple_format @user.intro %></div>
        <div><% if @user.email == current_user.email %>
         <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
        <% end %></div> 
      </div>
      <div class="clearfix"></div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong> <%= @commented_restaurants.count %></strong>已評論餐廳</h3>
        </div>
        <div class="panel-body">
          <% @commented_restaurants.each do |restaurant| %>
          <%= link_to restaurant_path(restaurant) do %>
            <div class="my-restaurant">
               <div>
                 <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>    
               </div>  
               <h5><%= restaurant.name %></h5>   
            </div> 
          <% end %>
          <% end %>
        </div>
      </div>

       
      
    </div>
  </div>
</div>