config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index , :show] do
    resources :comments,only:[:create, :destroy]
    #瀏覽所有餐廳的最進動態
    collection do
      get :feeds
    end
    #瀏覽個別餐廳的Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end

    member do
      get :dashboard
      post :like
      post :unlike
    end
  end
  resources :users,only: [:index ,:show , :edit, :update]

  resources :categories, only: :show
  resources :followships, only: [:create, :destroy]
  root "restaurants#index"

  namespace :admin do
    resources :restaurants 
    resources :categories
    root "restaurants#index"
  end


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, PhotoUploader
  belongs_to :category
  has_many :comments , dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  # before_action :authenticate_user!
  # before_action :authenticate_admin
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render:new
    end
  end

  def show
   
  end
  def edit
    
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurants_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)  
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :authenticate_user!
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all     # 加上這一行
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

    # POST /restaurants/:id/favorite
  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

 def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<h1><%= @restaurant.name %>'s Dashboard</h1>
<hr>
<ul>
  <li>有 <%= @restaurant.comments.count %></li>
  <li>這家餐廳的平均價位為＄xx</li>
  <li>有xx人收藏這家餐廳</li>
</ul>

app/views/restaurants/feeds.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" ><%= link_to "首頁", root_path %></li>
  <li role="presentation" class="active"><%= link_to "最新動態", feeds_restaurants_path %></li>
  <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
</ul>

<div class="row">
  <div class="col-xs-2">
  </div>

  <div class="col-xs-8">

    <h1>餐廳最新動態</h1>

     <div class="col-xs-6">
        <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">最新餐廳</h3>
          </div>
          <div class="panel-body">
              <% @recent_restaurants.each do |restaurant|%>
                <h4><%= link_to restaurant.name, restaurant_path(restaurant)%></h4>
                <p><%= restaurant.category.name %></p>
                <p><%= restaurant.description%></p>
                <hr>
              <% end %>
          </div>
        </div>
     </div> 
    <div class="col-xs-6">
        <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">最新評論</h3>
          </div>
          <div class="panel-body">
              <% @recent_comments.each do |comment|%>
                <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant)%></h4>
                <p><%= comment.content%></p>
                <p>by<%= link_to comment.user.name, user_path(comment.user)%></p>
                <hr>
              <% end %>
          </div>
        </div>
    </div>
  </div>

  

  <div class="col-xs-2">
  </div>

</div>

app/views/restaurants/index.html.erb
<div> 
  <ul class="nav nav-tabs">
    <li role="presentation" class="active"><%= link_to "首頁", root_path %></li>
    <li role="presentation" ><%= link_to "最新動態", feeds_restaurants_path %></li>
    <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
  </ul>
</div>
<div class="container">
  <div class="row">
    
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
    <!-- restaurants list，有多寫restaurant-item的class style -->
    <!-- <div class="restaurants clearfix">
      <% @restaurants.each do |restaurant| %>
        <div class="col-sm-6 col-md-4">
          <div class="restaurant-item">
            <%= image_tag restaurant.image, class: "img-responsive center-block" %>
            <div class="caption">
              <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
              <p class="label label-default"><%= restaurant.category.name %><p>
              <p><%= truncate(restaurant.description, length: 80) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>   -->
    <!-- 有generate kaminari paginate bootstrap style -->
   <!--  <div class="text-center">
      <%= paginate @restaurants %>
    </div> -->
    <br>

    <%= render partial:"shared/restaurant_list" %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>
       <%= link_to 'Dashboard', dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>
<!--        <% if @restaurant.is_favorited?(current_user) %>
          <%= link_to 'Unfavorite', unfavorite_restaurant_path(@restaurant), method: :post, class: "btn btn-info" %>
       <% else %>
          <%= link_to 'Favorite', favorite_restaurant_path(@restaurant), method: :post, class: "btn btn-primary" %>
       <% end %> -->
       <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
       
<!--        <% if @restaurant.is_liked?(current_user) %>
       <%= link_to 'Unlike', unlike_restaurant_path(@restaurant), method: :post, class: "btn btn-info" %>
       <% else %>
       <%= link_to 'Like', like_restaurant_path(@restaurant), method: :post, class: "btn btn-primary" %>
       <% end %> -->
       <%= render partial: "shared/like", locals: {restaurant: restaurant} %>

    </div>

    <hr>

  </div>
</div>
<div class="container">
  <div class="row">

   <% @restaurant.comments.each do |comment| %>
      <div>
        <h4><%= comment.user.email.split("@").first %></h4>
        <p><%= simple_format comment.content %></p>
        <p class="text-muted">
          <em><%= time_ago_in_words(comment.created_at) %> ago</em>   
          <% if current_user.admin? %>
                <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
          <% end %>
        </p>
      </div>
      <hr>
   <% end %>

   <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
    
  <% end %>
  </div>
</div>