config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index , :show] do
    resources :comments,only:[:create, :destroy]
    #瀏覽所有餐廳的最進動態
    collection do
      get :feeds
    end
    #瀏覽個別餐廳的Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end

    member do
      get :dashboard
      post :like
      post :unlike
    end
  end
  resources :users,only: [:index ,:show , :edit, :update]

  resources :categories, only: :show
  resources :followships, only: [:create, :destroy]
  root "restaurants#index"

  namespace :admin do
    resources :restaurants 
    resources :categories
    root "restaurants#index"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :restaurants , dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }
  
  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, PhotoUploader
  belongs_to :category
  has_many :comments , dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships
  
  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # private

  # def authenticate_admin
  #   unless current_user.admin?
  #     flash[:alert] = "Not allow!"
  #     redirect_to root_path
  #   end
  # end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant =Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end
  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  def create
    @followship = current_user.followships.build(following_id: params[:following_id])

    if @followship.save
      flash[:notice] = "Successfully followed"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    # where 會回傳物件集合(Array)，需要串接可取出單一物件的方法如 first
    @followship = current_user.followships.where(following_id: params[:id]).first
    @followship.destroy
    flash[:alert] = "Followship destroyed"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :authenticate_user!
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all     # 加上這一行
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

    # POST /restaurants/:id/favorite
  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

 def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :set_user, only: [:show, :edit, :update]
  
  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
  end
  def edit
    
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "user was successfully updated"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "user was failed to update"
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)  
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <!--    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
     Hi, <%= current_user.email %>
       <%= link_to('登出', destroy_user_session_path, method: :delete) %> |
       <%= link_to('修改密碼', edit_user_registration_path) %>
    <% else %>
      <%= link_to('註冊', new_user_registration_path) %> |
      <%= link_to('登入', new_user_session_path) %>
    <% end %> -->
    <!-- 導覽列 -->
     <nav class="navbar navbar-default">
       <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand">餐廳評論網</a>
         </div>
 
         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
           <ul class="pull-right text-right nav navbar-nav">
             <% if current_user %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
              <% end %>
             <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
             <li><%= link_to('Profile', user_path(current_user)) %></li>
             <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
             <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
             <% else %>
             <li><%= link_to('註冊', new_user_registration_path) %></li>
             <li><%= link_to('登入', new_user_session_path) %></li>
             <% end %>
           </ul>
         </div>
       </div>
     </nav>

     <% if flash[:notice] %>
     <div class="container">
       <div class="row">
         <div class="alert alert-success alert-dismissible" role="alert">
           <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <%= notice %>
         </div>
       </div>
     </div>
     <% end %>
 
     <% if flash[:alert] %>
     <div class="container">
       <div class="row">
          <div class="alert alert-danger alert-dismissible" role="alert">
           <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <%= alert %>
         </div>
       </div>
     </div>
     <% end %>



    <%= yield %>
    
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
 <% if current_user.following?(user)%>
    <%= link_to 'Unfollow', followship_path(user), method: :delete %>
 <% else %>
    <%= link_to 'Follow', followships_path(following_id: user), method: :post %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if restaurant.is_liked?(current_user) %>
  <%= link_to 'Unlike', unlike_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Like', like_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<div class="restaurants clearfix">
  <% @restaurants.each do |restaurant| %>
    <div class="col-sm-6 col-md-4">
       <div class="restaurant-item">
         <%= image_tag restaurant.image, class: "img-responsive center-block" %>
        <div class="caption">
          <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
          <p class="label label-default"><%= restaurant.category.name %><p>
          <p><%= truncate(restaurant.description, length: 80) %></p>
          <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
          
          <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
        </div>
      </div>
    </div>
  <% end %>
</div>  

<div class="text-center">
  <%= paginate @restaurants %>
</div>